/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Job {
  attempts: Generated<number>;
  createdAt: number;
  id: Generated<number>;
  payload: string;
  runAt: number;
  status: Generated<string>;
  type: string;
}

export interface OtpRequest {
  codeHash: string;
  createdAt: number;
  email: string;
  expiresAt: number;
  id: Generated<number>;
  type: Generated<string>;
}

export interface Session {
  createdAt: number;
  expiresAt: number;
  id: Generated<number>;
  token: string;
  userId: number;
}

export interface User {
  createdAt: number;
  deviceToken: string | null;
  email: string | null;
  id: Generated<number>;
  isGuest: Generated<number>;
  username: string;
}

export interface DB {
  jobs: Job;
  otpRequests: OtpRequest;
  sessions: Session;
  users: User;
}
